# Generated by Django 4.2 on 2023-05-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.CharField(default='-', max_length=122),
        ),
    ]
