# Generated by Django 4.2 on 2023-05-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_project_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.CharField(default='-', max_length=122),
        ),
    ]
